### ISSUE TITLE
翻页问题

### ISSUE THREAD

**Issue by mrchenxxx** [antdv-pro/antdv-pro#3]
在启用 pagination以后，total等设置ref的值，再次跳转别的菜单会报错，抱歉，由于个人原因未能够提供模拟数据
`const pagination = computed(() => ({
      total: 200, // total:total.value
      current:1,
      pageSize: 10,
}));`

报错：
`[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <RouterView> 
  at <AWatermark h-full="" flex="" flex-col=""  ... > 
  at <Anonymous hasSider=undefined prefixCls="ant-layout-content" tagName="main"  ... > 
  at <ALayoutContent ref="layoutRef" class="ant-pro-basicLayout-content" flex=""  ... > 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section" > 
  at <ALayout> 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section" > `

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'subTree')
    at getNextHostNode (runtime-core.esm-bundler.js:6319:46)
    at getNextHostNode (runtime-core.esm-bundler.js:6319:14)
    at getNextHostNode (runtime-core.esm-bundler.js:6319:14)
    at getNextHostNode (runtime-core.esm-bundler.js:6319:14)
    at getNextHostNode (runtime-core.esm-bundler.js:6319:14)
    at getNextHostNode (runtime-core.esm-bundler.js:6319:14)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5779:11)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (runtime-core.esm-bundler.js:5814:51)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:32)`

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at getPopupContainer (Options.js:123:59)
    at createVNode.getContainer (Trigger.js:665:51)
    at getParent3 (PortalWrapper.js:24:14)
    at PortalWrapper.js:145:25
    at runtime-core.esm-bundler.js:2675:88
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2655:19)
    at invokeArrayFns (shared.esm-bundler.js:77:10)
    at unmountComponent (runtime-core.esm-bundler.js:6289:7)`

**Comment by mrchenxxx** [comment]
抱歉。破案了 是antd的bug，把`showSizeChanger: false` 设置为false就好了
